# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  terraform: circleci/terraform@3.1

jobs:
  validate:
    executor: terraform/default
    steps:
      - checkout
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 1.3.4
      - terraform/fmt:
          path: ./terraform
      - terraform/validate:
          path: ./terraform
    working_directory: ~/terraform
workflows:
  validate:
    jobs:
      - validate