# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  terraform: circleci/terraform@3.1
  helm: circleci/helm@2.0.1

jobs:
  lint_helm_chart:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - helm/install-helm-client:
          version: 'v3.10.2'
      - run: helm lint "helm/automation-calculator" --strict

  validate_development_tf_cloud_env:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/env/development/tf_cloud
      - terraform/validate:
          path: ./terraform/env/development/tf_cloud

  validate_development_aws_env:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/env/development/aws/us-west-1
      - terraform/validate:
          path: ./terraform/env/development/aws/us-west-1

  #Validate was removed from here temporarily on 2023-01-06 because circleci orbs couldn't keep up with latest tf version
  validate_base_cluster_layer_module:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/modules/aws/base-cluster-layer
  
  #Validate was removed from here temporarily on 2023-01-06 because circleci orbs couldn't keep up with latest tf version
  validate_cluster_addons_module:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/modules/aws/cluster-addons-layer

  validate_main_rails_app_module:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/modules/aws/main_rails_app
      - terraform/validate:
          path: ./terraform/modules/aws/main_rails_app

  validate_networking_module:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/modules/aws/networking
      - terraform/validate:
          path: ./terraform/modules/aws/networking

workflows:
  validate:
    jobs:
      - lint_helm_chart      
      - validate_base_cluster_layer_module
      - validate_cluster_addons_module
      - validate_development_aws_env
      - validate_development_tf_cloud_env
      - validate_main_rails_app_module
      - validate_networking_module
