# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  terraform: circleci/terraform@3.1

jobs:
  validate_dev_env:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/aws/env/dev/global
      - terraform/validate:
          path: ./terraform/aws/env/dev/global
workflows:
  validate:
    jobs:
      - validate_dev_env