# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  terraform: circleci/terraform@3.1
  helm: circleci/helm@2.0.1

jobs:
  lint_helm_chart:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - helm/install-helm-client:
          version: 'v3.10.2'
      - run: helm lint "helm/automation-calculator" --strict

  validate_development_tf_cloud_env:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/env/development/tf_cloud
      - terraform/validate:
          path: ./terraform/env/development/tf_cloud

  validate_development_aws_base_cluster_layer:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/env/development/aws/us-west-1/base-cluster-layer
      - terraform/validate:
          path: ./terraform/env/development/aws/us-west-1/base-cluster-layer

  validate_development_aws_cluster_addons_layer:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/env/development/aws/us-west-1/cluster-addons-layer
      - terraform/validate:
          path: ./terraform/env/development/aws/us-west-1/
  
  validate_staging_tf_cloud_env:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/env/staging/tf_cloud
      - terraform/validate:
          path: ./terraform/env/staging/tf_cloud

  validate_staging_aws_base_cluster_layer:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/env/staging/aws/us-west-1/base-cluster-layer
      - terraform/validate:
          path: ./terraform/env/staging/aws/us-west-1/base-cluster-layer

  validate_staging_aws_cluster_addons_layer:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/env/staging/aws/us-west-1/cluster-addons-layer
      - terraform/validate:
          path: ./terraform/env/staging/aws/us-west-1/cluster-addons-layer

  validate_production_tf_cloud_env:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/env/production/tf_cloud
      - terraform/validate:
          path: ./terraform/env/production/tf_cloud

  validate_production_aws_base_cluster_layer:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/env/production/aws/us-west-1/base-cluster-layer
      - terraform/validate:
          path: ./terraform/env/production/aws/us-west-1/base-cluster-layer

  validate_production_aws_cluster_addons_layer:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/env/production/aws/us-west-1/cluster-addons-layer
      - terraform/validate:
          path: ./terraform/env/production/aws/us-west-1/cluster-addons-layer

  #Validate was removed from here temporarily on 2023-01-06 because circleci orbs couldn't keep up with latest tf version
  validate_tf_cloud_workspaces_module:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/modules/tf_cloud/tf_cloud_workspaces

  #Validate was removed from here temporarily on 2023-01-06 because circleci orbs couldn't keep up with latest tf version
  validate_base_cluster_layer_module:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/modules/aws/base-cluster-layer
  
  #Validate was removed from here temporarily on 2023-01-06 because circleci orbs couldn't keep up with latest tf version
  validate_cluster_addons_module:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/modules/aws/cluster-addons-layer

  validate_main_rails_app_module:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/modules/aws/main_rails_app
      - terraform/validate:
          path: ./terraform/modules/aws/main_rails_app

  validate_networking_module:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/modules/aws/networking
      - terraform/validate:
          path: ./terraform/modules/aws/networking

workflows:
  validate:
    jobs:
      - lint_helm_chart      
      - validate_base_cluster_layer_module
      - validate_cluster_addons_module
      - validate_tf_cloud_workspaces_module
      - validate_development_aws_base_cluster_layer
      - validate_development_aws_cluster_addons_layer
      - validate_development_tf_cloud_env
      - validate_staging_tf_cloud_env
      - validate_staging_aws_base_cluster_layer
      - validate_staging_aws_cluster_addons_layer
      - validate_production_tf_cloud_env
      - validate_production_aws_base_cluster_layer
      - validate_production_aws_cluster_addons_layer
      - validate_main_rails_app_module
      - validate_networking_module
