# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  terraform: circleci/terraform@3.1
  helm: circleci/helm@2.0.1

jobs:
  validate_dev_env:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/aws/env/dev/us-west-1
      - terraform/validate:
          path: ./terraform/aws/env/dev/us-west-1

  validate_main_rails_app_module:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/aws/modules/main_rails_app
      - terraform/validate:
          path: ./terraform/aws/modules/main_rails_app

  validate_networking_module:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./terraform/aws/modules/networking
      - terraform/validate:
          path: ./terraform/aws/modules/networking

  lint_helm_chart:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - helm/install-helm-client:
          version: '3.8.2'

workflows:
  validate:
    jobs:
      - validate_dev_env
      - validate_main_rails_app_module
      - validate_networking_module
      - lint_helm_chart