alarm_email                    = "steven.uray@automation-caluclations.net"
app_version                    = "0.9.6-841"
automation_calculator_app_host = "development.automation-calculations.io"
db_engine_version              = "16.13"
short_commit_hash              = "f3f7be1"
tfe_base_layer_workspace_name  = "ac_app_development_base_cluster_layer"
