alarm_email                    = "steven.uray@automation-caluclations.net"
app_version                    = "0.9.6-827"
automation_calculator_app_host = "automation-calculations.io"
db_engine_version              = "16.13"
tfe_base_layer_workspace_name  = "ac_app_production_base_cluster_layer"
