alarm_email                    = "steven.uray@automation-caluclations.net"
app_version                    = "0.9.6-830"
automation_calculator_app_host = "automation-calculations.io"
db_engine_version              = "16.13"
short_commit_hash              = ""
tfe_base_layer_workspace_name  = "ac_app_production_base_cluster_layer"
