apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "automation-calculator.fullname" . }}
  labels:
    {{- include "automation-calculator.labels" . | nindent 4 }}
  namespace: 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "automation-calculator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "automation-calculator.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
          - name: APP_HOSTNAME
            value: {{ .Values.ingress.host }}
          - name: GOOGLE_ANALYTICS_TRACKING_ID
            value: {{ .Values.googleAnalyticsTrackingID }}
          - name: RAILS_ENV
            value: {{ .Values.railsEnv }}
          - name: RAILS_LOG_TO_STDOUT
            value: "{{ .Values.logToStdout }}"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.kubernetesSecretObjectName }}
                key: databaseUrl
          - name: GITHUB_OAUTH_APP_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.kubernetesSecretObjectName }}
                key: githubOAuthAppId
          - name: GITHUB_OAUTH_APP_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.kubernetesSecretObjectName }}
                key: githubOAuthAppSecret
          - name: GOOGLE_OAUTH_APP_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.kubernetesSecretObjectName }}
                key: googleOAuthAppId
          - name: GOOGLE_OAUTH_APP_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.kubernetesSecretObjectName }}
                key: googleOAuthAppSecret
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.kubernetesSecretObjectName }}
                key: secretKeyBase
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    