apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "automation-calculator.fullname" . }}
  labels:
    {{- include "automation-calculator.labels" . | nindent 4 }}
  namespace: 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "automation-calculator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "automation-calculator.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
          - name: RAILS_ENV
            value: {{ .Values.railsEnv }}
          - name: RAILS_LOG_TO_STDOUT
            value: "{{ .Values.logToStdout }}"
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.kubernetesSecretObjectName }}
                key: databaseUsername
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.kubernetesSecretObjectName }}
                key: databasePassword
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.kubernetesSecretObjectName }}
                key: secretKeyBase
          - name: DATABASE_URL
            value: "postgres://user:password@localhost/my_database"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    