{{- $fullName := include "automation-calculator.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1

kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "automation-calculator.labels" . | nindent 4 }}

spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: http
                port:
                  number: 80