{{- $fullName := include "automation-calculator.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1

kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
    {{- include "automation-calculator.labels" . | nindent 4 }}

spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{$svcPort }}
