apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kubernetesSecretObjectName }}
  labels:
    {{- include "automation-calculator.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  databaseUrl: {{ .Values.secrets.databaseUrl }}
  githubOAuthAppId: {{ .Values.secrets.githubOAuthAppId }}
  githubOAuthAppSecret: {{ .Values.secrets.githubOAuthAppSecret }}
  secretKeyBase: {{ .Values.secrets.secretKeyBase }}
  
  
  