apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kubernetesSecretObjectName }}
  labels:
    {{- include "automation-calculator.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  secretKeyBase: {{ .Values.secrets.secretKeyBase }}
  databaseUsername: {{ .Values.secrets.databaseUsername }}
  databasePassword: {{ .Values.secrets.databasePassword }}
  