apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "automation-calculator.labels" . | nindent 4 }}
  name: {{ include "automation-calculator.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "automation-calculator.selectorLabels" . | nindent 4 }}
