# Default values for automation-calculator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

affinity: {}
fullnameOverride: automation-calculator
image:
  pullPolicy: Always
  repository: automationcalculationsci/automation-calculator
  tag: 0.4.2-550
ingress:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: "insert-cert-arn-here"
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/load-balancer-name: "automation-calculator-alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    
  host: "development.automation-calculations.io"
  tls: []
logToStdout: true
nameOverride: ""
namespace: automation-calculator
podAnnotations: {}
podSecurityContext: {}
railsEnv: production
replicaCount: 1
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi
secrets:
  databaseUrl: YOUR_DB_URL_HERE
  githubOAuthAppId: YOUR_GITHUB_OAUTH_APP_ID_HERE
  githubOAuthAppSecret: YOUR_GITHUB_OAUTH_APP_SECRET_HERE
  kubernetesSecretObjectName: automation-calculator-app-secrets
  secretKeyBase: YOUR_SECRET_KEY_BASE_HERE
securityContext: {}
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  externalTrafficPolicy: Local
  port: 80
  targetPort: 3000
  type: NodePort
tolerations: []
