# Default values for automation-calculator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

affinity: {}
fullnameOverride: automation-calculator
image:
  pullPolicy: Always
  repository: automationcalculationsci/automation-calculator
  tag: latest
ingress:
  annotations: {}
  tls: []
logToStdout: true
nameOverride: ""
namespace: automation-calculator
podAnnotations: {}
podSecurityContext: {}
railsEnv: production
replicaCount: 1
resources:
  limits:
    cpu: 4
    memory: 300Mi
  requests:
    cpu: 1
    memory: 128Mi
secrets:
  databaseUrl: YOUR_DB_URL_HERE
  kubernetesSecretObjectName: automation-calculator-app-secrets
  secretKeyBase: YOUR_SECRET_KEY_BASE_HERE
securityContext: {}
service:
  port: 80
  type: LoadBalancer
tolerations: []
