# Default values for automation-calculator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

affinity: {}
fullnameOverride: automation-calculator
image:
  pullPolicy: Always
  repository: automationcalculationsci/automation-calculator
  tag: 0.4.0-535
ingress:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/load-balancer-name: "automation-calculator-alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
  host: "development.automation-calculations.io"
  tls: []
logToStdout: true
nameOverride: ""
namespace: automation-calculator
podAnnotations: {}
podSecurityContext: {}
railsEnv: production
replicaCount: 1
resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests:
    cpu: 1
    memory: 128Mi
secrets:
  databaseUrl: YOUR_DB_URL_HERE
  kubernetesSecretObjectName: automation-calculator-app-secrets
  secretKeyBase: YOUR_SECRET_KEY_BASE_HERE
securityContext: {}
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  port: 80
  type: NodePort
tolerations: []
